name: "TorrServer"
description: "BitTorrent to HTTP streaming"
panel_icon: mdi:movie-play
url: "https://github.com/h1tch007/hass-addons/tree/main/TorrServer"
version: "0.128-0"
slug: "torrserver"
webui: "http://[HOST]:[PORT:8090]/"
watchdog: "http://[HOST]:[PORT:8090]/"
init: false
arch: 
  - amd64
startup: before
ports:
  8090/tcp: 8090
