name: "ENTcontrol"
description: "Управление контроллером Эра Новых Технологий"
panel_icon: mdi:movie-play
url: "https://github.com/h1tch007/hass-addons/tree/main/ENTcontrol"
version: "0.1-16"
slug: "entcontrol"
init: false
arch: 
  - amd64
startup: before
