name: "TorrServer (dev)"
description: "BitTorrent to HTTP streaming"
panel_icon: mdi:movie-play
url: "https://github.com/h1tch007/hass-addons/tree/main/TorrServer-dev"
version: "0.134-b15"
slug: "torrserver-dev"
watchdog: "http://[HOST]:[PORT:8090]/"
ingress: true
ingress_port: 8090
init: false
arch: 
  - amd64
map:
  - type: share
    read_only: False
    path: /opt
startup: before
ports:
  8090/tcp: 8090
